---
# tasks file for crio-container
#

- name: Add apt-key
  tags: install_crio
  shell: "{{ item }}"
  with_items:
  - curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ os_version }}/Release.key | sudo apt-key add -
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os_version }}/Release.key | sudo apt-key add -
  changed_when: false

- name: Add CRI-O repository
  tags: install_crio
  shell: "{{ item }}"
  with_items:
  - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os_version }}/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  - echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ os_version }}/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.list
  changed_when: false

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  changed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Install CRI-O
  tags: install_crio
  apt:
    name:
    - cri-o 
    - cri-o-runc

- name: Start and enable CRI-O service
  systemd:
    name: crio
    state: started
    enabled: yes

